//! QR文字列リスト（デバッグ支援）: タッチパネル（HMI）のQRリーダーに画面から
//! 読ませる文字列の登録・並び替えと、そのQRコードSVGの生成。QRコード画面
//! （`/qr-codes`）の裏側で、PLC書き込み経路とは完全に独立したユーティリティ。
//! backed by the `qr_strings` table (`migrations/0010_qr_strings.sql`).
//!
//! ## Invariants (docs/conventions.md)
//! - §2 (サービス層非依存): this service is `Clone` + `SqlitePool` +
//!   `BantoError` only - no tauri/axum/RBAC/HTTP. Authorization and audit are
//!   added by the wiring layer (`crate::rest` / `src-tauri`).
//! - §security: the `svg` field is machine-generated by the `qrcode` crate
//!   from our own backend - no user-controlled markup ever passes through it
//!   (the crate emits only `<svg>/<rect>/<path>` with numeric attributes), so
//!   the frontend's `{@html}` rendering of it satisfies the "self-generated,
//!   fully machine-generated output only" rule. Same precedent as the LAN
//!   access QR in `src-tauri`'s `qr_svg_for` / the settings screen.
//!
//! There is no `ListParams`/`ColumnMap` here on purpose: the list is a small,
//! user-ordered debug list, always returned in full in `sort_order` order
//! (グリッドのフィルタ/ソートは載せない)。並び替えは [`QrStringService::reorder`]
//! が ids 配列の添字を `sort_order` に一括反映する。

use banto_core::{BantoError, FieldError};
use qrcode::render::svg;
use qrcode::QrCode;
use serde::{Deserialize, Serialize};
use sqlx::SqlitePool;

use crate::support::{max_length_message, required_message};

/// QR text length cap. QR capacity itself tops out at 2953 BYTES (version
/// 40-L, byte mode), so 1000 CHARS of multi-byte Japanese could still
/// overflow it - which is why [`collect_errors`] additionally試しエンコード
/// して失敗を検証エラーとして返す (belt and suspenders; the manual notes the
/// practical limit).
const MAX_TEXT_LEN: usize = 1000;
const MAX_LABEL_LEN: usize = 100;

const RESOURCE: &str = "qr_strings";
const COLUMNS: &str = "id, label, text, sort_order, created_at";

/// A row of the `qr_strings` table, wire-shaped (camelCase), plus the
/// server-rendered QR code SVG for `text` (never stored - regenerated on
/// every read so it can never drift from `text`).
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, sqlx::FromRow)]
#[serde(rename_all = "camelCase")]
pub struct QrString {
    pub id: i64,
    pub label: String,
    pub text: String,
    pub sort_order: i64,
    pub created_at: String,
    /// Inline SVG of `text`'s QR code (see the module doc's §security note).
    /// Filled after fetch by [`with_svg`]; not a DB column.
    #[sqlx(default)]
    pub svg: String,
}

/// Create/update payload.
#[derive(Debug, Clone, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QrStringInput {
    #[serde(default)]
    pub label: String,
    pub text: String,
}

/// Render `data` as an inline SVG QR code - mirrors `src-tauri`'s
/// `qr_svg_for` (the LAN-access QR, spec §11.4) so the two QR features render
/// identically. Falls back to an empty string on an encoding failure rather
/// than panicking; create/update validation already rejects un-encodable
/// text, so an empty result can only happen for legacy rows.
fn qr_svg_for(data: &str) -> String {
    QrCode::new(data)
        .map(|code| code.render::<svg::Color>().min_dimensions(160, 160).build())
        .unwrap_or_default()
}

fn with_svg(mut row: QrString) -> QrString {
    row.svg = qr_svg_for(&row.text);
    row
}

/// Normalized (trimmed) fields from a [`QrStringInput`], bound on success.
struct Normalized {
    label: String,
    text: String,
}

/// Collect EVERY field violation (not just the first - mirrors
/// `crate::write_targets::collect_errors`).
fn collect_errors(input: &QrStringInput) -> (Vec<FieldError>, Normalized) {
    let mut errors: Vec<FieldError> = Vec::new();

    let trimmed_text = input.text.trim();
    if trimmed_text.is_empty() {
        errors.push(FieldError {
            field: "text".to_string(),
            message: required_message(),
        });
    } else if trimmed_text.chars().count() > MAX_TEXT_LEN {
        errors.push(FieldError {
            field: "text".to_string(),
            message: max_length_message(MAX_TEXT_LEN),
        });
    } else if QrCode::new(trimmed_text).is_err() {
        // 文字数上限内でもバイト数次第でQR容量を超え得る（モジュールコメント
        // 参照）。保存できたのにQRが出ない、を防ぐためここで弾く。
        errors.push(FieldError {
            field: "text".to_string(),
            message: "QRコードに変換できません（内容が長すぎる可能性があります）".to_string(),
        });
    }

    let trimmed_label = input.label.trim();
    if trimmed_label.chars().count() > MAX_LABEL_LEN {
        errors.push(FieldError {
            field: "label".to_string(),
            message: max_length_message(MAX_LABEL_LEN),
        });
    }

    (
        errors,
        Normalized {
            label: trimmed_label.to_string(),
            text: trimmed_text.to_string(),
        },
    )
}

/// Service layer for the `qr_strings` resource. Tauri/axum-independent
/// (invariant §2): only `SqlitePool` + `BantoError`.
#[derive(Clone)]
pub struct QrStringService {
    pool: SqlitePool,
}

impl QrStringService {
    pub fn new(pool: SqlitePool) -> Self {
        Self { pool }
    }

    /// The full list in display order (`sort_order` asc, `id` asc as the
    /// tie-breaker for legacy/equal values), each row with its rendered SVG.
    pub async fn list(&self) -> Result<Vec<QrString>, BantoError> {
        let rows: Vec<QrString> = sqlx::query_as(&format!(
            "SELECT {COLUMNS} FROM qr_strings ORDER BY sort_order ASC, id ASC"
        ))
        .fetch_all(&self.pool)
        .await
        .map_err(banto_storage::storage_error)?;
        Ok(rows.into_iter().map(with_svg).collect())
    }

    pub async fn get(&self, id: i64) -> Result<QrString, BantoError> {
        sqlx::query_as::<_, QrString>(&format!("SELECT {COLUMNS} FROM qr_strings WHERE id = ?"))
            .bind(id)
            .fetch_one(&self.pool)
            .await
            .map(with_svg)
            .map_err(|err| banto_storage::not_found(err, RESOURCE, id.to_string()))
    }

    /// Create at the end of the list (`MAX(sort_order) + 1`).
    pub async fn create(&self, input: QrStringInput) -> Result<QrString, BantoError> {
        let (errors, normalized) = collect_errors(&input);
        if !errors.is_empty() {
            return Err(BantoError::Validation {
                field_errors: errors,
            });
        }

        sqlx::query_as::<_, QrString>(&format!(
            "INSERT INTO qr_strings (label, text, sort_order) \
             VALUES (?, ?, (SELECT COALESCE(MAX(sort_order) + 1, 0) FROM qr_strings)) \
             RETURNING {COLUMNS}"
        ))
        .bind(&normalized.label)
        .bind(&normalized.text)
        .fetch_one(&self.pool)
        .await
        .map(with_svg)
        .map_err(banto_storage::storage_error)
    }

    /// Update `label`/`text` only - `sort_order` is owned by [`Self::reorder`].
    pub async fn update(&self, id: i64, input: QrStringInput) -> Result<QrString, BantoError> {
        let (errors, normalized) = collect_errors(&input);
        if !errors.is_empty() {
            return Err(BantoError::Validation {
                field_errors: errors,
            });
        }

        sqlx::query_as::<_, QrString>(&format!(
            "UPDATE qr_strings SET label = ?, text = ? WHERE id = ? RETURNING {COLUMNS}"
        ))
        .bind(&normalized.label)
        .bind(&normalized.text)
        .bind(id)
        .fetch_one(&self.pool)
        .await
        .map(with_svg)
        .map_err(|err| match err {
            sqlx::Error::RowNotFound => BantoError::NotFound {
                resource: RESOURCE.to_string(),
                id: id.to_string(),
            },
            other => banto_storage::storage_error(other),
        })
    }

    pub async fn delete(&self, id: i64) -> Result<(), BantoError> {
        let result = sqlx::query("DELETE FROM qr_strings WHERE id = ?")
            .bind(id)
            .execute(&self.pool)
            .await
            .map_err(banto_storage::storage_error)?;
        if result.rows_affected() == 0 {
            return Err(BantoError::NotFound {
                resource: RESOURCE.to_string(),
                id: id.to_string(),
            });
        }
        Ok(())
    }

    /// Bulk-set the display order: each id's `sort_order` becomes its index
    /// in `ids`. The frontend's ↑/↓ buttons send the FULL current list after
    /// a local swap (one round trip, no per-row move endpoints). `ids` must
    /// name every existing row exactly once - a stale list (e.g. another
    /// client added/removed a row since this one last loaded) is rejected as
    /// a validation error rather than silently corrupting the order.
    pub async fn reorder(&self, ids: Vec<i64>) -> Result<Vec<QrString>, BantoError> {
        let existing: Vec<i64> = sqlx::query_scalar("SELECT id FROM qr_strings ORDER BY id ASC")
            .fetch_all(&self.pool)
            .await
            .map_err(banto_storage::storage_error)?;
        let mut sorted = ids.clone();
        sorted.sort_unstable();
        if sorted != existing {
            return Err(BantoError::Validation {
                field_errors: vec![FieldError {
                    field: "ids".to_string(),
                    message: "並び替え対象が現在のリストと一致しません（画面を再読み込みしてください）"
                        .to_string(),
                }],
            });
        }

        let mut tx = self
            .pool
            .begin()
            .await
            .map_err(banto_storage::storage_error)?;
        for (index, id) in ids.iter().enumerate() {
            sqlx::query("UPDATE qr_strings SET sort_order = ? WHERE id = ?")
                .bind(index as i64)
                .bind(id)
                .execute(&mut *tx)
                .await
                .map_err(banto_storage::storage_error)?;
        }
        tx.commit().await.map_err(banto_storage::storage_error)?;
        self.list().await
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::db::init_db_memory;

    async fn setup() -> QrStringService {
        let pool = init_db_memory().await.expect("init_db_memory");
        QrStringService::new(pool)
    }

    fn sample(label: &str, text: &str) -> QrStringInput {
        QrStringInput {
            label: label.to_string(),
            text: text.to_string(),
        }
    }

    #[tokio::test]
    async fn create_then_get_round_trips_with_svg() {
        let svc = setup().await;
        let created = svc.create(sample("開始", "START")).await.expect("create");
        assert_eq!(created.label, "開始");
        assert_eq!(created.text, "START");
        assert_eq!(created.sort_order, 0);
        assert!(
            created.svg.contains("<svg"),
            "expected a rendered SVG, got: {}",
            created.svg
        );

        let fetched = svc.get(created.id).await.expect("get");
        assert_eq!(fetched, created);
    }

    #[tokio::test]
    async fn create_trims_label_and_text_and_appends_to_the_end() {
        let svc = setup().await;
        let first = svc.create(sample("", "A")).await.unwrap();
        let second = svc.create(sample("  ラベル  ", "  B  ")).await.unwrap();
        assert_eq!(first.sort_order, 0);
        assert_eq!(second.sort_order, 1);
        assert_eq!(second.label, "ラベル");
        assert_eq!(second.text, "B");
    }

    #[tokio::test]
    async fn create_allows_empty_label() {
        let svc = setup().await;
        let created = svc.create(sample("", "STOP")).await.expect("create");
        assert_eq!(created.label, "");
    }

    #[tokio::test]
    async fn create_rejects_empty_text() {
        let svc = setup().await;
        match svc.create(sample("x", "   ")).await.unwrap_err() {
            BantoError::Validation { field_errors } => {
                assert_eq!(field_errors[0].field, "text");
                assert_eq!(field_errors[0].message, required_message());
            }
            other => panic!("expected Validation, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn create_rejects_text_over_max_len() {
        let svc = setup().await;
        match svc
            .create(sample("x", &"a".repeat(MAX_TEXT_LEN + 1)))
            .await
            .unwrap_err()
        {
            BantoError::Validation { field_errors } => {
                assert_eq!(field_errors[0].field, "text");
                assert_eq!(field_errors[0].message, max_length_message(MAX_TEXT_LEN));
            }
            other => panic!("expected Validation, got {other:?}"),
        }
    }

    /// Within the char cap but over QR byte capacity (multi-byte chars):
    /// the trial-encode check must reject it as a friendly validation error,
    /// not save a row whose QR silently renders empty.
    #[tokio::test]
    async fn create_rejects_text_over_qr_byte_capacity() {
        let svc = setup().await;
        match svc
            .create(sample("x", &"あ".repeat(MAX_TEXT_LEN)))
            .await
            .unwrap_err()
        {
            BantoError::Validation { field_errors } => {
                assert_eq!(field_errors[0].field, "text");
                assert!(field_errors[0].message.contains("QRコードに変換できません"));
            }
            other => panic!("expected Validation, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn create_rejects_label_over_max_len() {
        let svc = setup().await;
        match svc
            .create(sample(&"あ".repeat(MAX_LABEL_LEN + 1), "OK"))
            .await
            .unwrap_err()
        {
            BantoError::Validation { field_errors } => {
                assert_eq!(field_errors[0].field, "label");
                assert_eq!(field_errors[0].message, max_length_message(MAX_LABEL_LEN));
            }
            other => panic!("expected Validation, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn update_changes_fields_and_rerenders_svg() {
        let svc = setup().await;
        let created = svc.create(sample("前", "BEFORE")).await.unwrap();
        let updated = svc
            .update(created.id, sample("後", "AFTER"))
            .await
            .expect("update");
        assert_eq!(updated.label, "後");
        assert_eq!(updated.text, "AFTER");
        assert_eq!(updated.sort_order, created.sort_order);
        assert!(updated.svg.contains("<svg"));
        assert_ne!(updated.svg, created.svg, "svg must follow the new text");
    }

    #[tokio::test]
    async fn update_missing_id_is_not_found() {
        let svc = setup().await;
        let err = svc.update(999, sample("x", "X")).await.unwrap_err();
        assert!(
            matches!(err, BantoError::NotFound { resource, id } if resource == RESOURCE && id == "999")
        );
    }

    #[tokio::test]
    async fn delete_then_get_is_not_found() {
        let svc = setup().await;
        let created = svc.create(sample("", "DOOMED")).await.unwrap();
        svc.delete(created.id).await.expect("delete");
        assert!(matches!(
            svc.get(created.id).await.unwrap_err(),
            BantoError::NotFound { .. }
        ));
    }

    #[tokio::test]
    async fn delete_missing_id_is_not_found() {
        let svc = setup().await;
        assert!(matches!(
            svc.delete(999).await.unwrap_err(),
            BantoError::NotFound { .. }
        ));
    }

    #[tokio::test]
    async fn reorder_sets_sort_order_by_index_and_list_follows() {
        let svc = setup().await;
        let a = svc.create(sample("", "A")).await.unwrap();
        let b = svc.create(sample("", "B")).await.unwrap();
        let c = svc.create(sample("", "C")).await.unwrap();

        let reordered = svc.reorder(vec![c.id, a.id, b.id]).await.expect("reorder");
        let texts: Vec<&str> = reordered.iter().map(|r| r.text.as_str()).collect();
        assert_eq!(texts, vec!["C", "A", "B"]);
        assert_eq!(
            reordered.iter().map(|r| r.sort_order).collect::<Vec<_>>(),
            vec![0, 1, 2]
        );

        let listed = svc.list().await.expect("list");
        assert_eq!(listed, reordered);
    }

    #[tokio::test]
    async fn reorder_rejects_a_stale_or_partial_id_list() {
        let svc = setup().await;
        let a = svc.create(sample("", "A")).await.unwrap();
        let _b = svc.create(sample("", "B")).await.unwrap();

        // Partial (missing b) and stale (unknown id) lists are both rejected.
        for ids in [vec![a.id], vec![a.id, 999]] {
            match svc.reorder(ids).await.unwrap_err() {
                BantoError::Validation { field_errors } => {
                    assert_eq!(field_errors[0].field, "ids")
                }
                other => panic!("expected Validation, got {other:?}"),
            }
        }
    }
}
